# Generated by Django 3.2.4 on 2021-07-12 16:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True, unique=True, verbose_name='类别名称')),
            ],
            options={
                'verbose_name': '新闻类别',
                'verbose_name_plural': '新闻类别',
                'db_table': 'tbCategory',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000, null=True, verbose_name='标题')),
                ('text', models.CharField(max_length=1000, null=True, verbose_name='正文')),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '新闻评论',
                'verbose_name_plural': '新闻评论',
                'db_table': 'tbComments',
            },
        ),
        migrations.CreateModel(
            name='Fname',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100, null=True, verbose_name='图片名')),
            ],
            options={
                'verbose_name': '新闻图片名',
                'verbose_name_plural': '新闻图片名',
                'db_table': 'tbFname',
            },
        ),
        migrations.CreateModel(
            name='Lable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True, verbose_name='标签')),
            ],
            options={
                'verbose_name': '新闻标签',
                'verbose_name_plural': '新闻标签',
                'db_table': 'tbLable',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000, verbose_name='标题')),
                ('author', models.CharField(max_length=50, null=True, verbose_name='作者')),
                ('create_date', models.DateField(null=True, verbose_name='发布日期')),
                ('description', models.CharField(max_length=2000, null=True, verbose_name='摘要')),
                ('text', models.CharField(max_length=2000, null=True, verbose_name='正文')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.category', verbose_name='新闻类别')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.comments', verbose_name='新闻评论')),
                ('comments_list', models.ManyToManyField(db_table='tbNewComments', related_name='new_comment', to='user.Comments', verbose_name='新闻评论表')),
                ('fname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.fname', verbose_name='图片名')),
                ('label', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.lable', verbose_name='标签')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
                'db_table': 'tb_News',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True, verbose_name='真实姓名')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机号码')),
                ('gender', models.IntegerField(default=0, null=True, verbose_name='性别')),
                ('birthday', models.DateField(null=True, verbose_name='出生年月')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='省份')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='城市')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='区/县')),
                ('id_card_number', models.CharField(max_length=18, null=True, verbose_name='身份证号码')),
                ('email', models.CharField(max_length=50, null=True, verbose_name='电子邮件')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('state', models.IntegerField(default=0, verbose_name='状态')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.comments', verbose_name='用户评论')),
                ('comments_list', models.ManyToManyField(db_table='tbUserComments', related_name='user_comment', to='user.Comments', verbose_name='用户评论表')),
                ('news', models.ManyToManyField(db_table='tbUserNews', related_name='user_news', to='user.New', verbose_name='收藏的新闻')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
            },
        ),
    ]
