# Generated by Django 3.2.5 on 2021-07-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210713_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.IntegerField(choices=[(0, '男'), (1, '女')], default=0, null=True, verbose_name='性别'),
        ),
    ]
